#!/bin/bash
# This hook is run after this virtualenv is activated.
export ASTER_ROOT="$ASTER_ROOT"
export ASTER_ROOT_DIR="$ASTER_ROOT/unstable"
export ASTER_ETC="$ASTER_ROOT/etc"
export ASTER_VERSION_DIR="$ASTER_ROOT/unstable"
export DEFINE_PROFILE_ASRUN="done"
export DEFINE_PROFILE_ASTER_VERSION="done"
export LD_LIBRARY_PATH="$ASTER_ROOT/public/scotch_5.1.11_esmumps/lib:$ASTER_ROOT/public/mumps-4.9.2/lib:$ASTER_ROOT/public/med-3.0.5/lib:$ASTER_ROOT/public/hdf5-1.8.8/lib:$LD_LIBRARY_PATH"
export OMP_NUM_THREADS="1"
export PATH="$ASTER_ROOT/public/metis-edf-4.1:$ASTER_ROOT/public/grace-5.1.21:$ASTER_ROOT/public/gmsh-2.5.0-Linux:$ASTER_ROOT/public/med-3.0.5:$ASTER_ROOT/public/hdf5-1.8.8:/usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.2:/bin:/usr/bin:$ASTER_ROOT/outils:$ASTER_ROOT/bin:$ASTER_ROOT/outils:/data/virtualenv/aster/bin:$PATH"
export PYTHONPATH="$ASTER_ROOT/lib/python2.7/site-packages:i$PYTHONPATH"
